# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy to server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        # username
        username: {{ secrets.sftp_username }}
        # your sftp server
        server: {{ secrets.sftp_server }}
        # will put all file under this path
        local_path: ./build
        # files will copy to under remote_path
        remote_path: ./gh-deploy/{{ github.event.repository.name }}
        # connection via sftp protocol only
        sftp_only: true
        # This operation will delete all files in the remote path before upload. Please be careful set this to true
        delete_remote_files: # optional
        password: {{ secrets.sftp_password }}
